services:
  - type: web
    name: math-quest
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase: 
          name: math-quest-db
          property: connectionString
    autoDeploy: true

databases:
  - name: math-quest-db
    plan: free 